# Spell icons, group C: Terep (terrain), Idő (time), Mana and Pusztítás (destruction).
import math
from lib import *


def disc(c, cx, cy, r, ch):
    for y in range(14):
        for x in range(14):
            if math.hypot(x + 0.5 - cx, y + 0.5 - cy) <= r:
                c[y][x] = ch


def ring(c, cx, cy, r, light, dark, thick=1.0):
    for y in range(14):
        for x in range(14):
            d = math.hypot(x + 0.5 - cx, y + 0.5 - cy)
            if r - thick <= d <= r:
                c[y][x] = light if (x + 0.5 - cx) + (y + 0.5 - cy) < 0 else dark


ICONS = {}

# ── sacrifice: a votive candle, its flame giving a mote of mana ──
c = canvas()
paste(c, 0, 0, grid('''
......l.....A.
.....lql...Az.
.....kqk....A.
.....jlj..z...
......j.......
.....909......
....99887.....
....99887.....
....98877.....
....9887......
....98876.....
...pp8876on...
..noppppponn..
...mnnnnnmm...
'''))
ICONS['sacrifice'] = rows(c)

# ── stepBack: a piece walks back to where it stood ──
c = canvas()
paste(c, 0, 0, grid('''
......AAAA....
....AA....A...
...A.......A..
..A.........z.
.zAz........z.
zzAzz.......z.
.zzz....98..z.
..z....9987...
.......9887...
........87....
.......9876...
.......9877...
.d.d..988776..
..............
'''))
ICONS['stepBack'] = rows(c)

# ── deathMark: a skull branded inside a red ring ──
c = canvas()
ring(c, 7, 7, 7.0, 'j', 'h', 1.5)
paste(c, 0, 0, grid('''
..............
..............
..............
.....9999.....
....999998....
...99999987...
...9009008...
...99990887...
....99..87....
....9.9.8.....
..............
..............
..............
..............
'''))
paste(c, 6, 11, grid('''
.i.
.h.
'''))
ICONS['deathMark'] = rows(c)

# ── manaDrain: a hungry maw draining a mana crystal ──
c = canvas()
paste(c, 0, 0, grid("""
..hiiiiiiiih..
.higgggggggih.
.hg98.gg.89gh.
..g98....89g..
...8.z..z.8...
...7..z...7...
......zBA.....
.....zBAzy....
....ABAAzyx...
....ABAzzyx...
....ABAzzyx...
....zAzzyxx...
.....zzyyx....
......yxw.....
"""))
ICONS['manaDrain'] = rows(c)

# ── wall: a raised section of mortared stone ──
c = canvas()
paste(c, 0, 0, grid('''
..............
..............
.ffffeffffeff.
.eeedbeeedbed.
.bbbbbbbbbbbb.
.edbeeedbeeec.
.dcbdddcbdddc.
.bbbbbbbbbbbb.
.eeedbeeedbed.
.dddcbdddcbdc.
.bbbbbbbbbbbb.
.edbeeedbeeec.
.dcbdddcbdddb.
.aaaaaaaaaaaa.
'''))
ICONS['wall'] = rows(c)

# ── barricade: sharpened stakes lashed together ──
c = canvas()
paste(c, 0, 0, grid('''
.f..........f.
.ed........ed.
..54......54..
...54....54...
....54..54....
.....5454.....
6666665466666.
5555554455554.
.....5445.....
....54..54....
...54....54...
..54......54..
.44........44.
.3..........3.
'''))
ICONS['barricade'] = rows(c)

# ── gravity: a heavy iron weight pulling everything down ──
c = canvas()
paste(c, 0, 0, grid('''
.....ddcc.....
....d....c....
....d....c....
...eddddddc...
..eedddddccb..
..eddddddccb..
.eedddddcccbb.
.eddddddccccb.
.edddddcccccb.
bbbbbbbbbbbbba
..............
.E....E....E..
EEE..EEE..EEE.
.D....D....D..
'''))
ICONS['gravity'] = rows(c)

# ── rewind: a clock with the hands turned back ──
c = canvas()
disc(c, 7.5, 7.5, 5.6, '8')
disc(c, 7.0, 7.0, 4.3, '9')
ring(c, 7.5, 7.5, 5.8, 'p', 'n', 1.3)
paste(c, 0, 0, grid('''
..............
..............
..............
..............
.......3......
.......3......
.......3......
.......333....
..............
..............
..............
..............
..............
..............
'''))
paste(c, 0, 0, grid('''
.zAAA.........
zA....A.......
A.............
A.............
zz............
.zz...........
'''))
paste(c, 0, 5, grid('''
.A.
AAA
'''))
ICONS['rewind'] = rows(c)

# ── earthquake: the ground splits and rocks jump ──
c = canvas()
paste(c, 0, 0, grid('''
..............
....e.....d...
...edc...dcb..
....c.....b...
.......e......
..............
666665........
5555546.666666
44444450555555
3444440.444444
33334440.44443
333330..044433
2222220..02222
1111111001111.
'''))
ICONS['earthquake'] = rows(c)

# ── dimensionShift: a 3×3 field folding into a portal ──
c = canvas()
paste(c, 0, 0, grid('''
..............
.FFFFFFFFFFFE.
.F...E...E..D.
.F...E...E..D.
.F...E...E..D.
.EEEEEJJEEEED.
.F..EJIIJ...D.
.F..EJHIJ...D.
.EEEEEJJEEEED.
.F...E...E..D.
.F...E...E..D.
.F...E...E..D.
.EDDDDDDDDDDD.
..............
'''))
put(c, 13, 0, 'J'); put(c, 0, 13, 'J')
ICONS['dimensionShift'] = rows(c)

# ── bloodPrice: blood paid for mana ──
c = canvas()
paste(c, 0, 0, grid('''
...j..........
...jj.........
..jjji........
..jjjii.......
.jNjiiih......
.jjiiiih......
.jiiiihh......
.iiiihhh..BA..
..ihhhg..BAzy.
...ggg..ABAzyx
........ABAzyx
........zAzyxx
.........zyxw.
..........xw..
'''))
ICONS['bloodPrice'] = rows(c)

# ── overcharge: lightning pouring into a crystal ──
c = canvas()
paste(c, 0, 0, grid('''
......BA...q..
.....BBzy.ql..
....ABAzyql...
...ABAAzql....
...ABAzqlll...
...ABAqqllq...
...ABAzzql....
...ABAzql.x...
...ABAql.yx...
...zAql.yxx...
....ql.yyxw...
...ql.zyxw....
..ql...xw.....
..l...........
'''))
ICONS['overcharge'] = rows(c)

# ── arcaneSurge: a burst of raw mana ──
c = canvas()
paste(c, 0, 0, grid('''
......A.......
......A.....z.
.z....B....z..
..z..zBz..z...
...zzABAzz....
....ABNBA.....
AABBBNNNBBBAAz
....ABNBA.....
...zzABAzz....
..z..zBz..z...
.z....B....z..
......A.......
......A.......
......z.......
'''))
ICONS['arcaneSurge'] = rows(c)

# ── gambit: a card played, a coin given away ──
c = canvas()
paste(c, 0, 0, grid('''
..............
...98888887...
...98888887...
...98..i887...
...98.iji87...
...98ijiji7...
...98.iji87...
...98..i887...
...98888887...
...9888888pqp.
...7777777pqpo
..........ppon
...........onn
..............
'''))
ICONS['gambit'] = rows(c)

# ── execution: the headsman's axe ──
c = canvas()
paste(c, 0, 0, grid("""
......ffe.....
.....fffed....
....ffeeddc...
....feeeddc...
...feeedddcb..
...feedd6cb...
....edd65b....
.....d65......
.....65.......
....65........
...65......i..
..65.......h..
.65...........
65............
"""))
ICONS['execution'] = rows(c)

# ── bishopSniper: a loaded crossbow ──
c = canvas()
paste(c, 0, 0, grid("""
......fe......
.....ffed.....
......ed......
....66ed66....
..66..ed..66..
.6....ed....5.
6.e...ed...e.5
5..e..54..e..4
....e.54.e....
.....e54e.....
......54......
.....oppo.....
......54......
......43......
"""))
ICONS['bishopSniper'] = rows(c)

# ── manaMage: a wizard's pointed hat ──
c = canvas()
paste(c, 0, 0, grid('''
..........zA..
.........yz...
........yyz...
.......yyzx...
......yyzzx...
......yzzxx...
.....yyzqxx...
.....yzqqqx...
....yyzzqxxx..
....pppppppo..
...ppqpppppon.
..yyyzzzxxxxw.
.yyzzzzzxxxxxw
..xxxxxxxxxww.
'''))
ICONS['manaMage'] = rows(c)

# ── manaDeposit: a chest holding mana for later ──
c = canvas()
paste(c, 0, 0, grid('''
......BA......
.....BAzy.....
......zy......
..6666666666..
.656666666665.
.55p555555p54.
.44p44pq44p43.
.66p66pn66p65.
.55p555555p54.
.55p555555p54.
.44p444444p43.
.33n333333n32.
..2222222222..
..............
'''))
ICONS['manaDeposit'] = rows(c)

# ── manaThirst: a goblet brimming with mana, a drop of blood falling in ──
c = canvas()
paste(c, 0, 0, grid('''
......i.......
.....iji......
......i.......
..............
.pBAAAAAAzzo..
.pAzzzzzzyyo..
.opppppppoon..
..oppppppon...
...oppppon....
.....pon......
.....pon......
....ppoon.....
..pppoooonn...
..nnnnnnnnm...
'''))
ICONS['manaThirst'] = rows(c)

# ── shieldBreaker: a war hammer splitting a shield ──
c = canvas()
paste(c, 0, 0, grid('''
.......ffed...
......fedcb...
......eddcbq..
.......dcb.qNq
.......65...q.
......65......
.pppp65nnnn...
.pfe65.edcn...
.pf65q.qdcn...
.pe6.qNq.cn...
..pd..q.cn....
..pedd.dcn....
...pedcnn.....
....ponn......
'''))
ICONS['shieldBreaker'] = rows(c)

# ── gravityWell: a vortex swallowing the light ──
c = canvas()
paste(c, 0, 0, grid('''
..............
.....FFEE.....
...FE.....E...
..F...DDD..D..
.F..DD...D..D.
.E.D..CCC.D.D.
.E.D.CaaaC.D..
.E.D.CaaaC.D..
..D.D.CCC..D..
..D..D....D.E.
...D..DDDD..E.
....E......F..
.....EEEFFF...
..............
'''))
ICONS['gravityWell'] = rows(c)

# ── manaArmageddon: a mana crystal bursting in red fire ──
c = canvas()
paste(c, 0, 0, grid('''
.k....j....k..
..k...j...k...
...j..BA.j....
......0Az.....
.....AB0zy....
jj..ABA0zyx.jj
...ABAz0yyx...
...ABz0zyyx...
...AB0Azyyx...
...z0zzyyxx...
....0zyyxw....
..j..zyxw..j..
.k....xw....k.
k.....j......k
'''))
ICONS['manaArmageddon'] = rows(c)

# ── dragonFire: a dragon's head breathing flame ──
c = canvas()
paste(c, 0, 0, grid("""
.e............
.de...........
..hh..........
..hihh........
.hiiiih.......
hiiqliih......
hiiiiiiiih....
.hhiiiiijkk...
..9.9.9jklqlk.
..hhhhjkqNqlk.
...hhhgjklqlk.
....hg..jkkj..
.........jj...
..............
"""))
ICONS['dragonFire'] = rows(c)

# ── doomsday: the reaper's scythe ──
c = canvas()
paste(c, 0, 0, grid("""
....fffff.....
..ffeeeeed....
.fed.....d5...
fe........4...
d.........4...
..........54..
...........4..
...........4..
...........54.
............4.
..j.........4.
.jkj........54.
..j..........4
............4.
"""))
ICONS['doomsday'] = rows(c)

# ── doom (Végzet): a pawn-shaped hole in reality, cracks running out of it ──
c = canvas()
paste(c, 0, 0, grid('''
B.............
.B9..FFFE.....
...9FC00CE....
....F0000E...B
....FC00CE.9B.
.....F00E.9...
....FC00CE....
.....F00E.....
.....F00E.....
....FC00CE..9B
..9FC0000CE9..
B9F00000000E..
..FFFFEEEEEE..
..............
'''))
ICONS['doom'] = rows(c)

HEADER = '''// Spell icons, group C – Terep (terrain), Idő (time), Mana and Pusztítás (destruction).
// 14×14 art + automatic outline = 16×16. Generated by scripts/icons/group_c.py.'''
write_ts('/home/claude/mana-chess/src/ui/pixel/art/spells_c.ts', 'SPELL_ICONS_C', ICONS, HEADER)
