// Style anchors for the spell icon set (14×14 art + auto outline = 16×16).
import type { SpriteSrc } from '../sprite';

const icon = (rows: string[]): SpriteSrc => ({ rows, outline: '0' });

export const ANCHORS: Record<string, SpriteSrc> = {
  meteor: icon([
    '..........kj..',
    '.........klkj.',
    '........kllk..',
    '.......jkllj..',
    '......jklqk...',
    '....ijkllqk...',
    '...ijklqqlj...',
    '..ijklqNqlj...',
    '.ijklqqqlkj...',
    '.ijkllqllkj...',
    '.iijklllkji...',
    '..iijkkkjii...',
    '...iiijjii....',
    '.....iiii.....',
  ]),
  shield: icon([
    '.eeeeeeeeeeee.',
    '.efffffffffed.',
    '.efyyyyyyyyed.',
    '.efyzzzzzzyed.',
    '.efyzAzzzzyed.',
    '.efyzzzzzzyed.',
    '.efyzzzzzzyed.',
    '.efyyzzzzyyed.',
    '..efyzzzzyed..',
    '..efyyzzyyed..',
    '...efyzzyed...',
    '....efyyed....',
    '.....effe.....',
    '......ee......',
  ]),
  bomb: icon([
    '..........q...',
    '.........qlq..',
    '........k.l...',
    '.......o......',
    '......no......',
    '....bcccb.....',
    '...bcdddcb....',
    '..bcdeedccb...',
    '..bcdedccca...',
    '..bccdcccca...',
    '..bcccccbaa...',
    '...bcccbaa....',
    '....baaaa.....',
    '..............',
  ]),
  hourglass: icon([
    '.oppppppppppo.',
    '.nnnnnnnnnnnn.',
    '..mBBBBBBBBm..',
    '..mBAAAAAABm..',
    '...mBAAAABm...',
    '....mBAABm....',
    '.....mzzm.....',
    '.....mzzm.....',
    '....mB..Bm....',
    '...mB.zz.Bm...',
    '..mB.zAAz.Bm..',
    '..mzAAAAAAzm..',
    '.nnnnnnnnnnnn.',
    '.oppppppppppo.',
  ]),
};
