import type { BotPersona } from '../persona';

// Nádi the normal: Gen Alpha, TikTok-szleng, szemüveges, kedvenc szava a „chillex”, és játék
// közben random brainrot neveket mond ({br}).
export const nadi: BotPersona = {
  talk: 1.1,
  voice: { pitch: 760, wave: 'square' },
  words: [
    'Tralalero Tralala',
    'Bombardiro Crocodilo',
    'Tung Tung Tung Sahur',
    'Brr Brr Patapim',
    'Ballerina Cappuccina',
    'Lirili Larila',
    'Chimpanzini Bananini',
    'Trippi Troppi',
    'Bombombini Gusini',
    'Cappuccino Assassino',
    'Frigo Camelo',
    'Udin Din Din Dun',
  ],
  lines: {
    intro: [
      'Yo, chillex! Kezdjük, tesó. {br}!',
      'Wassup! Ma full sigma mode-ban vagyok, no cap.',
      'Felvettem a szemüvegem. Most már látom a tábla auráját.',
      '{br}! …bocs, csak úgy kijött. Kezdjük!',
    ],
    playerMove: [
      'Ez a lépés… kinda mid, tesó.',
      'Chillex, chillex. Nem vagyok stresszes. Fr.',
      'Bro azt hiszi, ez rizz lépés volt.',
      'Ez a lépés nagyon Ohio, tesó.',
      '{br}!',
      'NPC lépés, de oké.',
      'Hmm. Ez most W vagy L? Szerintem L. No cap.',
      'Skibidi lépés. Nem tudom, mit jelent, de ez az.',
      'Bro lépett. Respect. Kicsit.',
      'Ez a lépés {br}-kompatibilis.',
    ],
    botMove: ['Sigma lépés. Nézd és tanulj.', 'Ez a lépés nagyon locked in volt.', '{br}! Ezt a lépést neki ajánlom.'],
    playerCapture: [
      'Bro elvitte a {pm}. Én cooked vagyok.',
      'Ez nem chillex volt, tesó.',
      'Tesó, ezt miért? A {pn} volt a GOAT.',
      '{br}! …ez fájt.',
    ],
    botCapture: ['Elvittem a {pd}! W! Hatalmas W!', 'Get rekt, tesó. Chillex.', 'Ez aura farming volt, sorry.', '{br} approves.'],
    playerSpell: ['„{spell}”? Ez valami új TikTok trend?', 'Bro varázsol. Ez nagyon brainrot.', 'Ez a spell bussin volt, nem hazudok.'],
    botSpell: ['„{spell}”! Sigma move, fr fr.', 'Nézd ezt: {br} jutsu!', 'Ezt TikTokon láttam. Működik.'],
    check: ['Sakk! Bro is cooked.', 'Sakk, tesó! Ez nagyon sigma volt.'],
    inCheck: ['Sakk?! Ez nem chillex, bro!', 'Nem, nem, nem. Ez L.'],
    blunder: ['Bro… ez nagyon Ohio lépés volt.', 'Ez a lépés mínusz ezer aura, tesó.', 'Ki tanított téged játszani, {br}?'],
    brilliant: ['Okay, ez lowkey nagyon jó volt.', 'Bro locked in. Respect.'],
    winning: ['Nyerek, tesó. Ez az én sigma arcom.', 'Easy W. Chillex.'],
    losing: ['Én most nagyon cooked vagyok.', 'Ez nagy L. Kikapcsolom a wifit. Vicc. Vagy nem.'],
    promotion: ['Glow up! A gyalog most már sigma.', 'Gyalog evolúció! {br}!'],
    idle: ['Tesó, TikTokot nézel közben? Mert én igen.', 'Bro AFK. {br}!', 'Chillex, de azért lépj már.'],
    chatter: [
      'Chillex. Ez a kedvenc szavam. Chill + relax. Zseniális, nem?',
      '{br}! {br}! …bocs, ez egy tic.',
      'Ma 4 órát TikTokoztam. Low, nem?',
      'Ki a jobb: {br} vagy {br}? Komoly kérdés.',
      'Six seven! …nem tudom, miért mondtam.',
      'Bro, ez a szemüveg plusz 50 aura.',
      'Ha nyerek, csinálok róla egy TikTokot. Ha vesztek, nem.',
      'Tesó, ez a meccs lowkey a kedvenc side questem.',
    ],
    win: ['GG EZ. Chillex. {br}!', 'W! Ezt posztolom, tesó.'],
    lose: ['GG, bro. Te vagy a GOAT. Ma.', 'L. Megyek, nézek egy kis brainrotot.'],
    draw: ['Döntetlen? Ez a legNPC-bb eredmény.'],
  },
};
